-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.people_type (
  type_id integer NOT NULL DEFAULT nextval('people_type_type_id_seq'::regclass),
  type_name text NOT NULL,
  CONSTRAINT people_type_pkey PRIMARY KEY (type_id)
);
CREATE TABLE public.stations (
  station_id integer NOT NULL DEFAULT nextval('stations_station_id_seq'::regclass),
  station_name text NOT NULL,
  province text DEFAULT 'อุดรธานี'::text,
  division text DEFAULT 'ภ.จว.อุดรธานี'::text,
  sort_order integer,
  CONSTRAINT stations_pkey PRIMARY KEY (station_id)
);
CREATE TABLE public.users (
  user_id integer NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
  username text NOT NULL,
  name text NOT NULL,
  pin_code text NOT NULL,
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['SuperAdmin'::text, 'Admin'::text, 'ผู้ดูแลระบบ'::text, 'User'::text, 'ผู้ใช้ทั่วไป'::text, 'External'::text, 'บุคคลภายนอก'::text])),
  station_id integer,
  auth_id uuid,
  division text,
  external_position text,
  prefix text,
  first_name text,
  last_name text,
  phone text,
  position text,
  created_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone,
  is_investigator boolean NOT NULL DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.stations(station_id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id)
);
CREATE TABLE public.people (
  id integer NOT NULL DEFAULT nextval('people_id_seq'::regclass),
  prefix text,
  first_name text NOT NULL,
  last_name text,
  nickname text,
  gender text,
  birth_date date,
  id_card text UNIQUE,
  contact_number text,
  house_number text,
  moo text,
  village_name text,
  tambon text,
  amphoe text,
  province text,
  location text,
  station_id integer,
  type_id integer,
  photo_url text,
  status text,
  medical_history text,
  guardian text,
  note1 text,
  note2 text,
  note3 text,
  user_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  aosm_name text,
  aosm_phone text,
  custody_status text NOT NULL DEFAULT 'ปกติ/กำลังรักษาตัว'::text CHECK (custody_status = ANY (ARRAY['ปกติ/กำลังรักษาตัว'::text, 'อยู่ในเรือนจำ'::text, 'เสียชีวิต'::text])) NOT VALI),
  created_by_user_id integer,
  CONSTRAINT people_pkey PRIMARY KEY (id),
  CONSTRAINT people_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.stations(station_id),
  CONSTRAINT people_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.people_type(type_id),
  CONSTRAINT people_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT people_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.visits (
  id integer NOT NULL DEFAULT nextval('visits_id_seq'::regclass),
  person_id integer NOT NULL,
  visit_date date NOT NULL,
  visit_time time without time zone NOT NULL,
  visitor_name text NOT NULL,
  visitor_station text,
  status_condition text,
  photo_url text,
  user_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  visit_category text NOT NULL DEFAULT 'general'::text CHECK (visit_category = ANY (ARRAY['general'::text, 'drug'::text, 'released'::text])),
  drug_test_result text CHECK (drug_test_result IS NULL OR (drug_test_result = ANY (ARRAY['ไม่พบสารเสพติด'::text, 'พบสารเสพติด'::text, 'ออกนอกพื้นที่ (ไปทำงาน)'::text, 'ออกนอกพื้นที่ (อยู่ในเรือนจำ)'::text]))),
  notes text,
  visit_status text CHECK (visit_status IS NULL OR (visit_status = ANY (ARRAY['อาการปกติ'::text, 'ปกติ'::text, 'เฝ้าระวัง'::text, 'เสี่ยงสูง'::text, 'เสียชีวิต'::text, 'อยู่ในเรือนจำ'::text, 'ออกนอกพื้นที่'::text, 'ส่งบำบัด'::text, 'ดำเนินคดี'::text]))),
  visitor_phone text,
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id),
  CONSTRAINT visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.guardians (
  id integer NOT NULL DEFAULT nextval('guardians_id_seq'::regclass),
  name text NOT NULL,
  position text,
  phone text,
  tambon text,
  amphoe text,
  station_name text,
  created_at timestamp with time zone DEFAULT now(),
  moo text,
  created_by_user_id integer,
  CONSTRAINT guardians_pkey PRIMARY KEY (id),
  CONSTRAINT guardians_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.activity_logs (
  id integer NOT NULL DEFAULT nextval('activity_logs_id_seq'::regclass),
  person_id integer NOT NULL,
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  log_time time without time zone NOT NULL DEFAULT CURRENT_TIME,
  description text NOT NULL,
  logged_by text,
  station text,
  is_auto boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id)
);
CREATE TABLE public.user_audit_logs (
  id bigint NOT NULL DEFAULT nextval('user_audit_logs_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_user_id integer,
  actor_auth_id uuid,
  actor_username text,
  actor_name text,
  actor_user_type text,
  actor_station_id integer,
  action text NOT NULL CHECK (action = ANY (ARRAY['person_view'::text, 'person_create'::text, 'person_update'::text, 'user_create'::text, 'user_update'::text, 'user_delete'::text, 'data_backup'::text, 'data_restore'::text, 'data_import'::text, 'drug_visit_delete'::text, 'drug_user_info_view'::text, 'drug_user_info_update'::text, 'drug_user_info_pdf_export'::text, 'drug_overview_pdf_export'::text, 'drug_overview_excel_export'::text, 'drug_overview_one_page_export'::text, 'drug_visit_search_excel_export'::text, 'psychiatric_visit_search_excel_export'::text, 'psychiatric_overview_excel_export'::text, 'roi_et_people_excel_export'::text, 'dealer_view'::text, 'dealer_status_update'::text, 'map_pdf_export'::text, 'one_police_one_village_create'::text, 'one_police_one_village_update'::text, 'one_police_one_village_excel_export'::text, 'prosecution_overview_load'::text, 'prosecution_overview_excel_export'::text, 'prosecution_person_search'::text, 'prosecution_case_search'::text, 'prosecution_case_create'::text, 'prosecution_case_view'::text, 'prosecution_case_update'::text, 'executive_dashboard_login'::text, 'user_login'::text, 'account_update'::text, 'pin_change'::text])),
  target_type text NOT NULL CHECK (target_type = ANY (ARRAY['person'::text, 'user'::text, 'system'::text])),
  target_person_id integer,
  target_user_id integer,
  target_name text,
  target_identifier text,
  description text,
  route_path text,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT user_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT user_audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(user_id),
  CONSTRAINT user_audit_logs_actor_auth_id_fkey FOREIGN KEY (actor_auth_id) REFERENCES auth.users(id),
  CONSTRAINT user_audit_logs_actor_station_id_fkey FOREIGN KEY (actor_station_id) REFERENCES public.stations(station_id)
);
CREATE TABLE public.drug_user_profiles (
  person_id integer NOT NULL,
  has_used_drugs text NOT NULL DEFAULT 'ไม่เคย'::text,
  drug_types ARRAY NOT NULL DEFAULT '{}'::text[],
  first_use_day integer,
  first_use_month integer,
  first_use_year integer,
  use_motivations ARRAY NOT NULL DEFAULT '{}'::text[],
  pills_per_use text,
  use_frequency_unit text,
  use_frequency_count text,
  supplier_count integer NOT NULL DEFAULT 0,
  last_use_drug_type text,
  last_use_day integer,
  last_use_month integer,
  last_use_year integer,
  last_use_hour integer,
  last_use_minute integer,
  last_use_amount text,
  last_supplier_sequence integer,
  payment_methods ARRAY NOT NULL DEFAULT '{}'::text[],
  transfer_sender_bank text,
  transfer_sender_account text,
  transfer_receiver_bank text,
  transfer_receiver_account text,
  payment_other_detail text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_user_id integer,
  created_by_name text,
  created_by_station text,
  updated_by_user_id integer,
  updated_by_name text,
  updated_by_station text,
  last_use_unit_price numeric,
  last_use_total_price numeric,
  created_by_division text,
  updated_by_division text,
  drug_user_status text NOT NULL DEFAULT 'ปกติ'::text CHECK (drug_user_status = ANY (ARRAY['ปกติ'::text, 'ออกนอกพื้นที่'::text, 'ถูกดำเนินคดี'::text])),
  CONSTRAINT drug_user_profiles_pkey PRIMARY KEY (person_id),
  CONSTRAINT drug_user_profiles_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id)
);
CREATE TABLE public.drug_user_suppliers (
  supplier_id bigint NOT NULL DEFAULT nextval('drug_user_suppliers_supplier_id_seq'::regclass),
  person_id integer NOT NULL,
  sequence_no integer NOT NULL,
  first_name text,
  last_name text,
  nickname text,
  has_more_info boolean NOT NULL DEFAULT false,
  id_card text,
  birth_day integer,
  birth_month integer,
  birth_year integer,
  house_number text,
  village_name text,
  phone text,
  line_id text,
  facebook text,
  province text,
  amphoe text,
  tambon text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  delivery_place text,
  CONSTRAINT drug_user_suppliers_pkey PRIMARY KEY (supplier_id),
  CONSTRAINT drug_user_suppliers_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id)
);
CREATE TABLE public.dealer_profiles (
  person_id integer NOT NULL,
  dealer_status text NOT NULL DEFAULT 'ยังไม่พบตัว'::text CHECK (dealer_status = ANY (ARRAY['ยังไม่พบตัว'::text, 'พบตัว'::text, 'ออกนอกพื้นที่'::text, 'อยู่ในเรือนจำ'::text, 'เสียชีวิต'::text, 'ยุติบทบาท'::text])),
  case_outcome text CHECK (case_outcome IS NULL OR (case_outcome = ANY (ARRAY['ไม่สามารถดำเนินคดีได้'::text, 'ดำเนินคดี'::text]))),
  charge_type ARRAY CHECK (charge_type IS NULL OR charge_type <@ ARRAY['เสพ'::text, 'ครอบครอง'::text, 'จำหน่าย'::text, 'สมคบสนับสนุน'::text]),
  seized_items text,
  expansion_result text CHECK (expansion_result IS NULL OR (expansion_result = ANY (ARRAY['ได้'::text, 'ไม่ได้'::text]))),
  notes text,
  updated_by_user_id integer,
  updated_by_name text,
  updated_by_station text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_user_id integer,
  created_by_name text,
  created_by_station text,
  created_by_division text,
  updated_by_division text,
  seized_yaba_pills integer CHECK (seized_yaba_pills IS NULL OR seized_yaba_pills >= 0),
  seized_ice_kg numeric CHECK (seized_ice_kg IS NULL OR seized_ice_kg >= 0::numeric),
  seized_other text,
  CONSTRAINT dealer_profiles_pkey PRIMARY KEY (person_id),
  CONSTRAINT dealer_profiles_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id),
  CONSTRAINT dealer_profiles_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT dealer_profiles_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.test (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  idcard text,
  CONSTRAINT test_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_registration_requests (
  id bigint NOT NULL DEFAULT nextval('user_registration_requests_id_seq'::regclass),
  username text NOT NULL CHECK (username ~ '^[0-9]+$'::text),
  pin_code_encrypted text NOT NULL,
  rank text NOT NULL CHECK (btrim(rank) <> ''::text),
  first_name text NOT NULL CHECK (btrim(first_name) <> ''::text),
  last_name text NOT NULL CHECK (btrim(last_name) <> ''::text),
  position text NOT NULL CHECK (btrim("position") <> ''::text),
  station_name text NOT NULL CHECK (btrim(station_name) <> ''::text),
  province text NOT NULL CHECK (btrim(province) <> ''::text),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text])),
  validation_error text,
  approved_user_id integer,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  phone text CHECK (phone IS NULL OR phone ~ '^[0-9]{9,10}$'::text),
  registration_type text NOT NULL DEFAULT 'police'::text CHECK (registration_type = ANY (ARRAY['police'::text, 'external'::text])),
  agency_name text,
  is_investigator boolean NOT NULL DEFAULT false,
  CONSTRAINT user_registration_requests_pkey PRIMARY KEY (id),
  CONSTRAINT user_registration_requests_approved_user_id_fkey FOREIGN KEY (approved_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.app_secrets (
  key text NOT NULL,
  secret_hash text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by_user_id integer,
  CONSTRAINT app_secrets_pkey PRIMARY KEY (key),
  CONSTRAINT app_secrets_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.patient_guardians (
  id integer NOT NULL DEFAULT nextval('patient_guardians_id_seq'::regclass),
  id_card text UNIQUE CHECK (id_card IS NULL OR id_card ~ '^[0-9]{13}$'::text),
  prefix text,
  first_name text NOT NULL CHECK (btrim(first_name) <> ''::text),
  last_name text NOT NULL CHECK (btrim(last_name) <> ''::text),
  phone text,
  auth_id uuid UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'revoked'::text])),
  created_by_user_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  station_id integer,
  CONSTRAINT patient_guardians_pkey PRIMARY KEY (id),
  CONSTRAINT patient_guardians_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id),
  CONSTRAINT patient_guardians_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT patient_guardians_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.stations(station_id)
);
CREATE TABLE public.guardian_patient_links (
  id integer NOT NULL DEFAULT nextval('guardian_patient_links_id_seq'::regclass),
  guardian_id integer NOT NULL,
  person_id integer NOT NULL,
  relationship text,
  created_by_user_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  revoked_by_user_id integer,
  revoke_reason text,
  reporting_paused_at timestamp with time zone,
  reporting_paused_by_user_id integer,
  approval_status text NOT NULL DEFAULT 'approved'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text])),
  approved_at timestamp with time zone,
  approved_by_user_id integer,
  CONSTRAINT guardian_patient_links_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_patient_links_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES public.patient_guardians(id),
  CONSTRAINT guardian_patient_links_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id),
  CONSTRAINT guardian_patient_links_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT guardian_patient_links_revoked_by_user_id_fkey FOREIGN KEY (revoked_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT guardian_patient_links_reporting_paused_by_user_id_fkey FOREIGN KEY (reporting_paused_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT guardian_patient_links_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.guardian_reports (
  id bigint NOT NULL DEFAULT nextval('guardian_reports_id_seq'::regclass),
  person_id integer NOT NULL,
  guardian_id integer NOT NULL,
  report_date date NOT NULL,
  met_patient text NOT NULL CHECK (met_patient = ANY (ARRAY['พบตัว'::text, 'ไม่พบตัว'::text])),
  medication text NOT NULL CHECK (medication = ANY (ARRAY['กินครบ'::text, 'ขาดบางมื้อ'::text, 'ไม่ได้กิน'::text, 'ไม่ทราบ'::text])),
  symptoms ARRAY NOT NULL DEFAULT '{}'::text[],
  risk_behaviors ARRAY NOT NULL DEFAULT '{}'::text[],
  note text,
  severity smallint NOT NULL DEFAULT LEAST(2, (((
CASE
    WHEN (met_patient = 'ไม่พบตัว'::text) THEN 1
    ELSE 0
END +
CASE
    WHEN (medication = ANY (ARRAY['ขาดบางมื้อ'::text, 'ไม่ได้กิน'::text])) THEN 1
    ELSE 0
END) +
CASE
    WHEN (cardinality(symptoms) > 0) THEN 1
    ELSE 0
END) +
CASE
    WHEN (cardinality(risk_behaviors) > 0) THEN 1
    ELSE 0
END)),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_agent text,
  cancelled_at timestamp with time zone,
  cancelled_by_guardian_id integer,
  CONSTRAINT guardian_reports_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_reports_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id),
  CONSTRAINT guardian_reports_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES public.patient_guardians(id),
  CONSTRAINT guardian_reports_cancelled_by_guardian_id_fkey FOREIGN KEY (cancelled_by_guardian_id) REFERENCES public.patient_guardians(id)
);
CREATE TABLE public.person_report_status (
  person_id integer NOT NULL,
  last_report_date date,
  last_report_severity smallint,
  missed_days integer NOT NULL DEFAULT 0,
  alert_source text NOT NULL DEFAULT 'none'::text CHECK (alert_source = ANY (ARRAY['none'::text, 'abnormal'::text, 'missing'::text])),
  alert_level text NOT NULL DEFAULT 'ปกติ'::text CHECK (alert_level = ANY (ARRAY['ปกติ'::text, 'เฝ้าระวัง'::text, 'เสี่ยงสูง'::text])),
  since date,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT person_report_status_pkey PRIMARY KEY (person_id),
  CONSTRAINT person_report_status_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id)
);
CREATE TABLE public.guardian_report_settings (
  id integer NOT NULL DEFAULT nextval('guardian_report_settings_id_seq'::regclass),
  division text UNIQUE,
  watch_after_missed_days integer NOT NULL DEFAULT 2,
  high_risk_after_missed_days integer NOT NULL DEFAULT 4,
  high_risk_consecutive_abnormal integer NOT NULL DEFAULT 2,
  recover_after_normal_days integer NOT NULL DEFAULT 3,
  count_weekends boolean NOT NULL DEFAULT true,
  updated_by_user_id integer,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT guardian_report_settings_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_report_settings_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.guardian_login_attempts (
  id bigint NOT NULL DEFAULT nextval('guardian_login_attempts_id_seq'::regclass),
  id_card text NOT NULL,
  succeeded boolean NOT NULL,
  ip_hash text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT guardian_login_attempts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.one_village_one_police_assignments (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  village_key text NOT NULL UNIQUE,
  station_name text NOT NULL,
  district text NOT NULL,
  subdistrict text NOT NULL,
  village_name text NOT NULL,
  village_no text NOT NULL,
  police_rank text NOT NULL CHECK (police_rank = ANY (ARRAY['พ.ต.อ.'::text, 'พ.ต.ท.'::text, 'พ.ต.ต.'::text, 'ร.ต.อ.'::text, 'ร.ต.ท.'::text, 'ร.ต.ต.'::text, 'ด.ต.'::text, 'จ.ส.ต.'::text, 'ส.ต.อ.'::text, 'ส.ต.ท.'::text, 'ส.ต.ต.'::text])),
  first_name text NOT NULL,
  last_name text NOT NULL,
  position text NOT NULL,
  phone text NOT NULL,
  order_file_path text,
  order_file_name text,
  updated_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT one_village_one_police_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT one_village_one_police_assignments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.one_village_one_police_subdistrict_officers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  area_key text NOT NULL UNIQUE,
  station_name text NOT NULL,
  district text NOT NULL,
  subdistrict text NOT NULL,
  police_rank text NOT NULL CHECK (police_rank = ANY (ARRAY['พ.ต.อ.'::text, 'พ.ต.ท.'::text, 'พ.ต.ต.'::text, 'ร.ต.อ.'::text, 'ร.ต.ท.'::text, 'ร.ต.ต.'::text, 'ด.ต.'::text, 'จ.ส.ต.'::text, 'ส.ต.อ.'::text, 'ส.ต.ท.'::text, 'ส.ต.ต.'::text])),
  first_name text NOT NULL,
  last_name text NOT NULL,
  position text NOT NULL,
  phone text NOT NULL,
  updated_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT one_village_one_police_subdistrict_officers_pkey PRIMARY KEY (id),
  CONSTRAINT one_village_one_police_subdistrict_officers_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.one_village_one_police_station_orders (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  station_name text NOT NULL UNIQUE,
  order_file_path text NOT NULL,
  order_file_name text NOT NULL,
  updated_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT one_village_one_police_station_orders_pkey PRIMARY KEY (id),
  CONSTRAINT one_village_one_police_station_orders_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.prosecution_cases (
  id bigint NOT NULL DEFAULT nextval('prosecution_cases_id_seq'::regclass),
  case_number text NOT NULL CHECK (btrim(case_number) <> ''::text),
  person_id integer NOT NULL,
  division text NOT NULL,
  station_id integer NOT NULL,
  investigator_user_id integer NOT NULL,
  accuser_name text NOT NULL CHECK (btrim(accuser_name) <> ''::text),
  offenses ARRAY NOT NULL DEFAULT '{}'::text[] CHECK (cardinality(offenses) > 0),
  other_offense text,
  circumstances text,
  case_result text,
  case_status text NOT NULL DEFAULT 'in_progress'::text CHECK (case_status = ANY (ARRAY['in_progress'::text, 'completed'::text])),
  created_by_user_id integer NOT NULL,
  updated_by_user_id integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  other_offenses ARRAY NOT NULL DEFAULT '{}'::text[],
  completed_at timestamp with time zone,
  case_date date NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT prosecution_cases_pkey PRIMARY KEY (id),
  CONSTRAINT prosecution_cases_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id),
  CONSTRAINT prosecution_cases_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.stations(station_id),
  CONSTRAINT prosecution_cases_investigator_user_id_fkey FOREIGN KEY (investigator_user_id) REFERENCES public.users(user_id),
  CONSTRAINT prosecution_cases_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT prosecution_cases_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.person_guardian_contacts (
  id bigint NOT NULL DEFAULT nextval('person_guardian_contacts_id_seq'::regclass),
  person_id integer NOT NULL,
  prefix text,
  first_name text NOT NULL CHECK (btrim(first_name) <> ''::text),
  last_name text NOT NULL CHECK (btrim(last_name) <> ''::text),
  phone text CHECK (phone IS NULL OR phone ~ '^[0-9]{9,10}$'::text),
  relationship text,
  created_by_user_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT person_guardian_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT person_guardian_contacts_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id),
  CONSTRAINT person_guardian_contacts_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id)
);